
# 1. key 
# 2. build

name: deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.1'

      - name: Install dependencies 
        run: go mod download 


      - name: Build app
        run: go build -o telbot ./telebot 


    # add key 
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts

      # - name: Deploy with rsync
      #   run:   rsync -avz ./dist/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/api


      - name: Stop app and deploy
      run: |
        ssh  ${{ secrets.USER }}@${{ secrets.SSH_HOST }}  "pkill -x telbot"  
        scp  ./telbot ${{ secrets.USER }}@${{ secrets.SSH_HOST }:/var/www/api/


      - name: Set env vars and start app
      run: |
        ssh  ${{ secrets.USER }}@${{ secrets.SSH_HOST }} "\
          cd /var/www/api && \
          nohup ./telbot >> ./telbot.log 2>&1 &\
        "
      env:
        TOKEN: ${{ secrets.TOKEN }}
        CHATID: ${{ secrets.CHATID }}
        DB: ${{ secrets.DB }}